INSERT INTO ROLE VALUES (1, 'ROLE_ADMIN'), (2, 'ROLE_USER');
INSERT INTO PASSENGER_TYPE VALUES ('ADULT'),('CHILD'),('INFANT');
INSERT INTO AIRPLANE VALUES (1, 'A');
INSERT INTO CLASS VALUES ('Economy', 1, 1, 1), ('Business', 1, 1, 1);
INSERT INTO SEAT VALUES ('Economy', 1, 1), ('Business', 1, 1);